require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

RSpec/DescribeClass:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false
